### ISSUE TITLE
Setup_DTC.sh and TRACE_FILE

### ISSUE THREAD

**Issue by pavel1murat** [Mu2e/mu2e-pcie-utils#12]
the Setup_DTC.sh scripts defines TRACE_FILE and other TRACE settings. 
In a multi-user environment this leads to conflicts.

Could everything TRACE-related be moved out ? - thanks

**Comment by rrivera747** [comment]
otsdaq is the supported multi-user approach for Mu2e. I believe we have now fixed the multi-user conflicts in the ots launching tool.
