### ISSUE TITLE
setup_ots.sh vs Setup_DTC.sh

### ISSUE THREAD

**Issue by pavel1murat** [Mu2e/mu2e-pcie-utils#13]
it would be helpful to have a uniform naming convention for the setup scripts 

- no capitalization is preferred: if any capitalization is used, one has to type more switching the capitalization register and remember the capitalization rules

**Comment by rrivera747** [comment]
The preferred punctuation for ots and artdaq is lower case. The preferred punctuation for the DTC and CFO is upper case.
