### ISSUE TITLE
DTC constructor and destructor

### ISSUE THREAD

**Issue by pavel1murat** [Mu2e/mu2e-pcie-utils#14]
C++ class **_DTC_** interits from **_DTC_Register_**. As a consequence, the DTC constructor and destructor, in a hidden way,  write into the DTC registers, which changes the state of the DTC. Sometimes, one  just needs to test reading of the DTC registers, w/o changing the DTC register contents (the DTC may be running).

DTC is a software construct, so I suggest taking the register I/O operations outside the constructor and destructor and making them separate functions, called explicitly only when initialization of the hardware is needed.

ALso a **DTC is not a DTC register, a DTC has multiple registers.** 
Therefore, using inheritance is not the right technical approach here - we may want to fix that.

**Comment by eflumerf** [comment]
The DTC_Register**s** class represents the DTC register space. The DTC class extends the knowledge of the DTC register space with methods that perform DMA operations on the device.

**Comment by rrivera747** [comment]
The initialization of the constructor can now be skipped. For example, when instantiated by otsdaq, no register calls are made during the DTC () constructor.

**Comment by pavel1murat** [comment]
I understand that one can skip the initialization, this also doesn't help much as it forces the users to re-implement all nontrivial logic already implemented in the DTC/DTC_Registers constructors

https://github.com/Mu2e/mu2e_pcie_utils/blob/develop/dtcInterfaceLib/DTC_Registers.cpp#L79

What I meant was simple and different: the DTC constructor should not write into the the DTC registers: in multithreaded, and moreover in multiprocess environment changing the hardware status upon construction of the software objects might lead to very difficult to find consequences, and therefore should be avoided.
