### ISSUE TITLE
problems with reading the tracker data using PCIE kernel drivers v2_09_00, v2_08_00, and (possibly) v2_04_01

### ISSUE THREAD

**Issue by pavel1murat** [Mu2e/mu2e-pcie-utils#25]
We tried using PCIE kernel drivers v2_09_00, v2_08_00, and v2_04_01  on mu2edaq09 to read the tracker data. 

- with either a v2_09_00 or v2_08_00 driver installed, an attempt to read the digi data from a tracker DRAC leads to an immediate freese (hang) of the computer, recovery requires a  reboot.
- with the v2_04_01 driver, one can read the digi data for (typically) several minutes, after which the DTC starts reporting zero length reads.

**Comment by pavel1murat** [comment]
the problem might have been due to the inconsistency between the versions of several kernel modules installed by dkms
after that has been fixed, don't see hang ups any more

- now we're using the PCIE kernel modules v2_09_00

**Comment by rrivera747** [comment]
Tracker team as confirmed issue fixed.
