### ISSUE TITLE
machine (mu2edaq08) crashes when taking data

### ISSUE THREAD

**Issue by corrodis** [Mu2e/mu2e-pcie-utils#27]
mu2edaq08 crashed multiple times when taking data. As far as I can see, the crashes are not related to specific data rates. I had crashes with different data rates from the sensors and different read intervals. 
driver: mu2e_pcie_utils/2.09.00, 3.10.0-1160.102.1.el7.x86_64, x86_64: installed
DTC firmware: 0x9004: 0x23091215 (I'll need help to load a newer version in the new scheme to test a newer firmware version)

Some logs and a screenshot of how I found the machine can be found here: https://dbweb8.fnal.gov:8443/ECL/mu2e/E/show?e=1853

**Comment by corrodis** [comment]
same behavior with DTC2023Oct27_09_22.1 firmware version

**Comment by pavel1murat** [comment]
just got mu2edaq09 shut down in the very beginning of the datataking. 

- the DTC firmware version :
```
mu2etrk@mu2edaq09:~/test_stand/pasha_018>my_cntl read 0x9004
0x2309021
```
- the PCIE driver version : 
```
mu2etrk@mu2edaq09:~/test_stand/pasha_020>dkms status 
pcie_linux_kernel_module/2.04.01, 3.10.0-1160.102.1.el7.x86_64, x86_64: installed (original_module exists)
```

**Comment by rrivera747** [comment]
@corrodis is this still happening?

**Comment by corrodis** [comment]
no, fortunately, I haven't seen this happening in a long time
